// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
 default: {
  marquee: {
    name: "marquee",
    type: "registry:ui",
    registryDependencies: undefined,
    files: ["registry/default/magicui/marquee.tsx"],
    component: React.lazy(
      () => import("@/registry/default/magicui/marquee.tsx"),
    ),
    source: "",
    category: "undefined",
    subcategory: "undefined",
    chunks: [],
  },
 }
};